### ISSUE TITLE
Find a better heuristic for detecting a Magento 2.x store

### ISSUE THREAD

**Issue by DrewML** [magento/m2-devtools#13]
## This issue is a:

- [ ] Bug
- [X] Feature suggestion
- [ ] Documentation issue
- [ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             | N/A |
| Browser + version           | N/A |
| node.js version (`node -v`) | N/A |
| npm version (`npm -v`)      | N/A |

## Description
The [code used to detect a Magento 2 store](https://github.com/magento/m2-devtools/blob/d4fc44a9baa7da0aa97a1f695fdbb63aa3c9fe74/extension/devtools.js#L39-L47) and show the tab in DevTools is not great. It checks for one of the following 3 classes:

- `page-layout-1column`,
- `page-layout-2columns-left`,
- `page-layout-checkout`

I'm sure there are pages this breaks on, so we should find a better way.

Requirements:
- Should work on the large majority of Magento 2.x stores
- Should not require installing any additional modules

## Expected result:
A more stable implementation of the `isMagento2Store` function.

**Comment by oscarpas** [comment]
How about checking if the document cookie contains a Magento specific substring?

**Comment by Vinai** [comment]
A guest that only visits pages served from the FPC will not have a cookie. Not sure if that is a relevant scenario for collecting the data for the bundling config.

**Comment by DrewML** [comment]
@Vinai That is good to know. We use the detection mechanism for determining when to show the `Magento` tab in DevTools, so relying on the cookie would def have problems.

**Comment by Vinai** [comment]
How about checking for the presence of `/static/version[0-9]+/frontend/.+/.+/.+/requirejs/require.js`? Is that possible?

**Comment by DrewML** [comment]
@Vinai Brilliant! That should work well.

**Comment by DrewML** [comment]
Thanks again @Vinai! Ended up going with

```js
/\/static\/version\d+\/frontend\/.+\/.+\/requirejs\/require(?:\.min)?\.js/
```

**Comment by DrewML** [comment]
Heh, turns out that wasn't quite enough. Hopefully the newest variant works:

https://github.com/magento/m2-devtools/blob/a68c24acd1a5b2348d17821f568abefaeafc5e49/extension/devtools.js#L37-L44
