### ISSUE TITLE
Documentation: js minification has to be disabled

### ISSUE THREAD

**Issue by davidverholen** [magento/m2-devtools#36]
## This issue is a:

- [ ] Bug
- [ ] Feature suggestion
- [x] Documentation issue
- [ ] Other (Please Specify)

## Description

If Magento js minification is enabled during setup:static-content:deploy, the rjs optimizer cannot find the modules as they are renamed by magento. Seems obvious if you think about it but I was hanging there a bit ;)

**Comment by DrewML** [comment]
Nice catch! I hadn't even thought of that. Want to send a PR up with a note in [the instructions](https://github.com/magento/m2-devtools/blob/689dbadff3d419c0f98052e8cb841158762685d7/docs/panels/PostBundleInstructions.md)?

**Comment by Vinai** [comment]
How about just disabling it automatically?

**Comment by DrewML** [comment]
> How about just disabling it automatically?

Yeah, that actually sounds more ideal. Rather have the tool do the right thing instead of just throwing up. Can you think of any downsides?

**Comment by Vinai** [comment]
@Januszpl When `Magento_BundleConfig` is installed and enabled, the minification is done by the requirejs optimizer running uglify (or alternatively the google closure compiler depending on the config), so there is no need do any additional minification. It's part of the bundling process.

**Comment by Januszpl** [comment]
@Vinai so you have requirejs optimizer config configured the way it will uglify files in all those directories? 
1 - pub/static/**frontend**/Vendor/theme/.../*.js - yes 
2 - pub/static/**_requirejs**/frontend/Vendor/theme/...../require-config.js
3 - pub/static/**adminhtml**/Vendor/theme/..../*.js

I so far run `requirejs.optimize(rjsConfig);` trough each theme/locale and dir is nr 1 option, and baseUrl (nr 1 option with _tmp).

**Comment by DrewML** [comment]
Since we've set criteria here for how this works, I've opened up a ticket to track the actual work and make it more visible for those looking to contribute.

I'll close this ticket out and we'll track in #47
