### ISSUE TITLE
Ready?

### ISSUE THREAD

**Issue by shakyShane** [magento/m2-devtools#4]
Thanks for this!

Can I point traffic from config-gen yet so I don't need to continue development? :)

I think there's a missing piece (the config for loading the bundles) but other than that, this seems to work well, great job!

**Comment by DrewML** [comment]
@shakyShane I figured you might find this before I announced 😛.

Go for it! The bundling code is heavily WIP, but should be ready for early users real soon. Just need to get the PHP module up.

**Comment by DrewML** [comment]
I just pushed up the Magento module that does basic code loading, and opened up #6 and #8 to address the bugs I know of with it.

**Comment by DrewML** [comment]
#8 is fixed now, too. Think we just need some light docs for early adopters and then you can send people this way.

**Comment by DrewML** [comment]
Now that those issues are fixed, I'll close this out. There are surely still bugs, but I'm hoping at this point the community will be able to help report/fix as we find them.
