### ISSUE TITLE
Javascript Bundling not working correctly with Amazon modules enabled

### ISSUE THREAD

**Issue by dverkade** [magento/m2-devtools#43]
## This issue is a:

- Bug

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             | 2.3.0 |
| Browser + version           | Chrome 71.0.3578.80 |
| node.js version (`node -v`) | v6.14.3 |
| npm version (`npm -v`)      | 3.10.10 |

## Description

With the Amazon modules enabled (Amazon_Payments, Amazon_Login & Amazon_Core) the bundled 
javascript throws an error. This can be fixed by disabling the Amazon modules in Magento and removing any the entries in the build.js file referencing Amazon.

## Expected result:

Javascript bundeling should work correctly with Amazon modules enabled. 

## Screenshots

This is the first error thrown:
![image](https://user-images.githubusercontent.com/1058480/49998576-eb234500-ff94-11e8-8341-feee9d01d949.png)

This will result and the following additional errors: 
![image](https://user-images.githubusercontent.com/1058480/49998619-07bf7d00-ff95-11e8-9795-fa4508a9c434.png)

Once the Amazon modules are disabled first error is gone. Additional errors are also gone.

**Comment by DrewML** [comment]
Thanks Danny! Would you be able to deploy this broken build to somewhere publicly-accessible like in #44?

**Comment by DrewML** [comment]
Without running the code, I was able to spot at least 1 of the issues from the screenshot.

The `Amazon_Payments` module is loading `uiRegistry` using [a _synchronous_ `require` call](https://github.com/amzn/amazon-payments-magento-2-plugin/blob/5b4d2ce3b01859e2d184cd987928a27f1bc19c43/src/Payment/view/frontend/web/js/amazon-widgets-loader.js#L16):

```js
var registry = require('uiRegistry');

if (registry.get('amazonPayment') !== undefined) {
    var amazonPayment = registry.get('amazonPayment');

    define([amazonPayment.widgetUrl], function () {
        'use strict';

        //after amazon widgets file as loaded

    });
}
```

Because of the sync usage of `require`, that module is going to blow up anytime its code executes before the code of the module that it is obtaining with `require('dependency')`.

**Comment by dverkade** [comment]
@DrewML thanks! Not really a bug in Magento but of this 3rd party integration of Amazon.

**Comment by dverkade** [comment]
As a workaround I removed all Amazon references from my build.js file, which resolves this issue.

**Comment by DrewML** [comment]
> As a workaround I removed all Amazon references from my build.js file, which resolves this issue.

ah yeah, that works too! I'm going to leave this issue open until it's resolved in the Amazon Payments module, so others with the problem can find this easily. I might just bake in a config fix for Amazon Payments until then 🤔

**Comment by DrewML** [comment]
This was fixed in the upstream module https://github.com/amzn/amazon-payments-magento-2-plugin/pull/410
