### ISSUE TITLE
Information about the project

### ISSUE THREAD

**Issue by alinalexandru** [magento/m2-devtools#58]
Hello,
Is this project still supported.

I am looking to a solution for advanced bundling.
This solution seems to be a good one and I want to know if I should start using it and contribute if needed.

**Comment by Januszpl** [comment]
Good question.
I guess @DrewML has now other priorities and for sure projects like that require help of other people. I think any PR would be welcome but hopefully he can say more.

**Comment by DrewML** [comment]
"Supported" is a fun word 😅

If you have problems with this project, I'll gladly accept bug reports and PRs.

Having said that, my plan is to deprecate this bundling functionality when we have a new solution out (in the coming months). For now, there are folks using this project with success.

**Comment by rossmc** [comment]
@DrewML New solution, in coming months?

Can you tell us more? Will it use rjsOptimiser, will it require a Magento upgrade etc?

:)

**Comment by DrewML** [comment]
The project for bundling is [now on Github](https://github.com/DrewML/baler). It'll be moving over to the Magento org as we get a bit closer to feature complete.

@rossmc It doesn't use the `r.js` optimizer, and no upgrades required :). It will require having `node` available during a build, and having an additional module installed to load the bundles.
